import type { NextPage } from 'next'
import Head from 'next/head'
import {Box } from "@mui/material"
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Razvan head</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ backgroundColor: 'primary.main' }}></Box>
        <h1 className={styles.title}>
          Razvan body
        </h1>
      </main> 

      <footer className={styles.footer}>
          Razvan footer
        
      </footer>
    </div>
  )
}

export default Home
