import type { NextPage } from 'next'
import Head from 'next/head'
import { Box } from "@mui/material"
import Hero from "../src/hero/Hero"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Razvan head</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main> 

      <footer>
          Razvan footer
      </footer>
    </div>
  )
}

export default Home
